export const CASE_STATUS = {
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  WITHDRAW_REQUESTED: "WITHDRAW_REQUESTED",
  WITHDRAWN: "WITHDRAWN",
  CLOSED: "CLOSED",
};
